# Generated by Django 4.0.6 on 2022-07-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_a', models.TextField()),
                ('alternative_b', models.TextField()),
                ('alternative_c', models.TextField()),
                ('alternative_d', models.TextField()),
                ('answer_status', models.BooleanField(default=False)),
                ('question_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Sem resposta', 'Sem resposta')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('alternative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternative')),
            ],
        ),
    ]
